# Generated by Django 5.1 on 2025-12-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Entrenadores',
            },
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_membresia', models.CharField(max_length=50, verbose_name='Tipo de Membresía')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_meses', models.IntegerField(verbose_name='Duración (Meses)')),
                ('beneficios', models.TextField()),
                ('num_sesiones_incluidas', models.IntegerField(verbose_name='Número de Sesiones')),
                ('es_activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('horario', models.CharField(help_text='Ej: Lunes y Miércoles 10:00 AM', max_length=100)),
                ('duracion_minutos', models.IntegerField()),
                ('cupo_maximo', models.IntegerField()),
                ('costo_clase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_dificultad', models.CharField(max_length=50)),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='members.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento_membresia', models.DateField()),
                ('membresia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios', to='members.membresia')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('objetivo', models.CharField(max_length=100)),
                ('descripcion_ejercicios', models.TextField()),
                ('frecuencia', models.CharField(help_text='Ej: 3 veces por semana', max_length=50)),
                ('duracion_semanas', models.IntegerField()),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_asignadas', to='members.entrenador')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='members.socio')),
            ],
            options={
                'verbose_name': 'Rutina Personalizada',
                'verbose_name_plural': 'Rutinas Personalizadas',
            },
        ),
        migrations.CreateModel(
            name='ReservaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado_reserva', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Confirmada', max_length=50)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='members.clase')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='members.socio')),
            ],
            options={
                'verbose_name': 'Reserva de Clase',
                'verbose_name_plural': 'Reservas de Clases',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta de Crédito/Débito'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('concepto', models.CharField(max_length=100)),
                ('estado_pago', models.CharField(default='Pagado', max_length=50)),
                ('membresia_pagada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membresia')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='members.socio')),
            ],
        ),
    ]
